### ISSUE TITLE
Expo integration

### ISSUE THREAD

**Issue by SamueleBarbiera** [Mokshit06/typewind#31]
### Discussed in https://github.com/Mokshit06/typewind/discussions/27

<div type='discussions-op-text'>

<sup>Originally posted by **SamueleBarbiera** February  7, 2023</sup>
Can it be used lime nativewind or even implementend in the t3-turbo stack?</div>

**Comment by SamueleBarbiera** [comment]
I tried to run in it in a solito app but it gave me this error 
<img width="1496" alt="Screenshot 2023-02-24 alle 22 06 53" src="https://user-images.githubusercontent.com/80902731/221292065-4e08115c-9896-4e96-9b65-633fa0f4bef9.png">

**Comment by SamueleBarbiera** [comment]
ok now at least i get the error from ts on the ide cause of the missing types 
```
Property 'bg_blue_500' does not exist on type 'TypewindError<"Typewind's types haven't been generated. Run `npx typewind generate` or follow the docs at https://typewind.vercel.app/docs/installation">'.
Translation: You're trying to access bg_blue_500 on an object that doesn't contain it.
```

and when I run the ```npx typewind generate``` command I get this error 

```
TypeError: Cannot read properties of undefined (reading 'some')
    at /Users/samuelebarbiera/Desktop/solito-typewind/node_modules/typewind/dist/cli.js:182:35
```

if u want to reproduce this issue this is the repo: https://github.com/SamueleBarbiera/solito-typewind-turborepo

**Comment by SamueleBarbiera** [comment]
I set up the swc plugin integration by the way! and it doesn't give me the error above https://github.com/Mokshit06/typewind/issues/31#issuecomment-1444491289
@Mokshit06 @kavinvalli

**Comment by kavinvalli** [comment]
Oh it works? Will check this out once. Thanks for the update!

**Comment by SamueleBarbiera** [comment]
> Oh it works? Will check this out once. Thanks for the update!

not yet @kavinvalli ... the only problem is the types generator that gives the error , and if we solve that it can even run on expo!!

```
TypeError: Cannot read properties of undefined (reading 'some')
    at /Users/samuelebarbiera/Desktop/solito-typewind/node_modules/typewind/dist/cli.js:182:35
```

**Comment by SamueleBarbiera** [comment]
oh by the way i'll try to fork the repo and solve the error and put the lib in my turbo repo as a workspace dependency
